import uuid from 'react-uuid';

var Products =
[{
    "id": uuid(),
    "title": "strawberries",
    "type": "fruit",
    "price": 18.12,
    "rating": 4,
    "image": 'Strawberries.jpg'
  }, {
    "id": uuid(),
    "title": "mozzarella cheese",
    "type": "dairy",
    "price": 11.14,
    "rating": 4,
    "image": 'Mozzarella-Cheese.jpg'
  }, {
    "id": uuid(),
    "title": "Avocado",
    "type": "fruit",
    "price": 14.18,
    "rating": 1,
    "image": 'avocado.jpg'
  }, {
    "id": uuid(),
    "title": "sirloin steak",
    "type": "meat",
    "price": 38.18,
    "image": 'sirloin.jpg'
  }, {
    "id": uuid(),
    "title": "Homemade bread",
    "type": "bakery",
    "price": 17.48,
    "rating": 3,
    "image": 'homemade-bread.jpg'
  }, {
    "id": uuid(),
    "title": "milk",
    "type": "dairy",
    "price": 21.32,
    "rating": 0,
    "image": 'glass-of-milk.jpg'
  }, {
    "id": uuid(),
    "title": "eggs",
    "type": "dairy",
    "price": 27.14,
    "rating": 2,
    "image": 'eggs.jpg'
  }, {
    "id": uuid(),
    "title": "Potatoes",
    "type": "vegetable",
    "price": 18.32,
    "rating": 3,
    "image": 'Potatoes.jpg'
  }, {
    "id": uuid(),
    "title": "blueberries",
    "type": "fruit",
    "price": 19.49,
    "rating": 4,
    "image": 'Blueberry.png'
  }, {
    "id": uuid(),
    "title": "beetroot",
    "type": "vegetable",
    "price": 17.11,
    "rating": 2,
    "image": 'Beetroot.jpg'
  }, {
    "id": uuid(),
    "title": "Peaches",
    "type": "fruit",
    "price": 29.45,
    "rating": 4,
    "image": 'Peaches.jpg'
  }, {
    "id": uuid(),
    "title": "goat cheese",
    "type": "dairy",
    "price": 17.68,
    "rating": 4,
    "image": 'Goat-Cheese.jpg'
  }, {
    "id": uuid(),
    "title": "parsley",
    "type": "vegetable",
    "price": 18.19,
    "rating": 2,
    "image": 'parsley.jpg'
  }, {
    "id": uuid(),
    "title": "Bananas",
    "type": "fruit",
    "price": 28.59,
    "rating": 4,
    "image": 'Bananas.jpg'
  }, {
    "id": uuid(),
    "title": "Lemons",
    "type": "fruit",
    "price": 15.79,
    "rating": 5,
    "image": 'lemons.jpg'
  }, {
    "id": uuid(),
    "title": "cauliflower",
    "type": "vegetable",
    "price": 14.77,
    "rating": 0,
    "image": 'cauliflower.jpg'
  }, {
    "id": uuid(),
    "title": "Tomatoes",
    "type": "fruit",
    "price": 16.3,
    "rating": 2,
    "image": 'Tomatoes.jpg'
  }, {
    "id": uuid(),
    "title": "Pears",
    "type": "fruit",
    "price": 13.02,
    "rating": 2,
    "image": 'Pears.jpg'
  }, {
    "id": uuid(),
    "title": "Green beans",
    "type": "vegetable",
    "price": 28.79,
    "rating": 1,
    "image": 'Green-bean.jpg'
  }, {
    "id": uuid(),
    "title": "portabello mushrooms",
    "type": "vegetable",
    "price": 20.31,
    "rating": 1,
    "image": 'portabello_mushrooms.jpg'
  }, {
    "id": uuid(),
    "title": "cabbage",
    "type": "vegetable",
    "price": 27.35,
    "rating": 0,
    "image": 'Cabbage.jpeg'
  }, {
    "id": uuid(),
    "title": "Watermelon",
    "type": "fruit",
    "price": 15.12,
    "image": 'Watermelon.jpg'
  }, {
    "id": uuid(),
    "title": "celery",
    "type": "vegetable",
    "price": 16.76,
    "image": 'celery.jpg'
  }, {
    "id": uuid(),
    "title": "grapefruit",
    "type": "fruit",
    "price": 21.48,
    "rating": 4,
    "image": 'grapefruits.png'
  }, {
    "id": uuid(),
    "title": "Broccoli",
    "type": "vegetable",
    "price": 29.66,
    "rating": 4,
    "image": 'Broccoli1.jpg'
  }, {
    "id": uuid(),
    "title": "Parmigiano-Reggiano",
    "type": "dairy",
    "price": 22.7,
    "rating": 2,
    "image": 'Parmigiano-Reggiano.jpg'
  }, {
    "id": uuid(),
    "title": "Honey",
    "type": "dairy",
    "price": 17.01,
    "rating": 2,
    "image": 'Honey2.jpg'
  }, {
    "id": uuid(),
    "title": "cucumber",
    "type": "vegetable",
    "price": 14.05,
    "rating": 1,
    "image": 'cucumber.jpg'
  }, {
    "id": uuid(),
    "title": "lady pink apples",
    "type": "fruit",
    "price": 28.86,
    "rating": 2,
    "image": 'pink-lady-apples.jpg'
  }, {
    "id": uuid(),
    "title": "mangoes",
    "type": "fruit",
    "price": 26.21,
    "rating": 4,
    "image": 'mango.jpg'
  }, {
    "id": uuid(),
    "title": "Ricotta cheese",
    "type": "dairy",
    "price": 27.81,
    "rating": 5,
    "image": 'ricotta-cheese.jpg'
  }, {
    "id": uuid(),
    "title": "croissant",
    "type": "bakery",
    "price": 18.5,
    "rating": 4,
    "image": 'croissant1.jpg'
  }, {
    "id": uuid(),
    "title": "Granola",
    "type": "dairy",
    "price": 29.97,
    "rating": 3,
    "image": 'Homemade-Granola.jpg'
  }, {
    "id": uuid(),
    "title": "oranges",
    "type": "fruit",
    "price": 25.26,
    "rating": 5,
    "image": 'oranges.jpg'
  }, {
    "id": uuid(),
    "title": "Greek Yogurt",
    "type": "dairy",
    "price": 27.61,
    "rating": 4,
    "image": 'Greek_Yogurt.jpg'
  }, {
    "id": uuid(),
    "title": "zucchini",
    "type": "vegetable",
    "price": 22.48,
    "rating": 5,
    "image": 'zucchini.jpg'
  }, {
    "id": uuid(),
    "title": "Cherries",
    "type": "fruit",
    "price": 14.35,
    "rating": 5,
    "image": 'cherries.jpg'
  }, {
    "id": uuid(),
    "title": "onions",
    "type": "vegetable",
    "price": 22.97,
    "rating": 4,
    "image": 'onions.jpg'
  }, {
    "id": uuid(),
    "title": "Ground beef",
    "type": "meat",
    "price": 29.73,
    "rating": 5,
    "image": 'Ground_beef.jpg'
  }, {
    "id": uuid(),
    "title": "Corn",
    "type": "vegetable",
    "price": 13.55,
    "rating": 2,
    "image": 'Corn.jpg'
  }, {
    "id": uuid(),
    "title": "pita",
    "type": "bakery",
    "price": 28.96,
    "rating": 5,
    "image": 'pita.jpg'
  }, {
    "id": uuid(),
    "title": "rasberries",
    "type": "fruit",
    "price": 21.01,
    "rating": 4,
    "image": 'rasberries.jpg'
  }, {
    "id": uuid(),
    "title": "carrots",
    "type": "vegetable",
    "price": 25.88,
    "rating": 0,
    "image": 'carrots.jpeg'
  }, {
    "id": uuid(),
    "title": "baguette",
    "type": "bakery",
    "price": 15.18,
    "rating": 1,
    "image": 'baguette.jpg'
  }, {
    "id": uuid(),
    "title": "Plums",
    "type": "fruit",
    "price": 19.18,
    "rating": 1,
    "image": 'Plums.jpg'
  }, {
    "id": uuid(),
    "title": "chicken thighs",
    "type": "meat",
    "price": 25.13,
    "rating": 3,
    "image": 'chicken_thigh.jpg'
  }, {
    "id": uuid(),
    "title": "eggplant",
    "type": "vegetable",
    "price": 26.03,
    "rating": 4,
    "image": 'eggplant1.jpg'
  }, {
    "id": uuid(),
    "title": "grapes",
    "type": "fruit",
    "price": 15.19,
    "rating": 4,
    "image": 'grapes.jpg'
  }, {
    "id": uuid(),
    "title": "blue cheese",
    "type": "dairy",
    "price": 25.62,
    "image": 'blue_cheese.jpg'
  }, {
    "id": uuid(),
    "title": "Asparagus",
    "type": "vegetable",
    "price": 18.95,
    "rating": 3,
    "image": 'Asparagus.jpg'
  }]

  export { Products };